steps:
  # Step 1: Install Ruby and Jekyll dependencies
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        apt-get update
        apt-get install -y ruby-full build-essential zlib1g-dev
        gem install jekyll bundler

  # Step 2: Install the site dependencies (if you have a Gemfile)
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gem install bundler
        bundle install

  # Step 3: Build the Jekyll site
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        jekyll build

  # Step 4: Deploy the built site to Google Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'jekyll-site'
      - '--image'
      - 'gcr.io/$PROJECT_ID/jekyll-site'
      - '--platform'
      - 'managed'
      - '--region'
      - 'us-central1'
      - '--allow-unauthenticated'
